name: Deploy to Firebase
description: Deploy to Firebase Project
inputs:
  identity_provider:
    description: 'The identity provider for the workload identity'
    required: true
  service_account_email:
    description: 'The service account email'
    required: true
  project_id:
    description: 'The project ID'
    required: true
  firebase_config:
    description: 'The firebase config'
    required: true
  preview:
    description: 'Deploy to preview environment'
    required: false
    default: 'no'
  build_command:
    description: 'The build command'
    required: true
  repo_token:
    description: 'The GitHub token'
    required: false

runs:
  using: composite
  steps:
    - name: 🐍 Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip
        cache-dependency-path: ./functions/python/requirements.txt

    # this is a requirement for the arcgis package: https://github.com/Esri/arcgis-python-api/issues/1299#issuecomment-1185375010
    - name: Install libkrb5 for Kerberos
      shell: bash
      run: |
        sudo apt install -y libkrb5-dev
        pip install requests-kerberos

    - name: 🚀 Deploy Firebase
      uses: agrc/firebase-website-deploy-composite-action@v1
      with:
        identity-provider: ${{ inputs.identity_provider }}
        service-account-email: ${{ inputs.service_account_email }}
        project-id: ${{ inputs.project_id }}
        prebuild-command: |
          cd functions/python
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          cd ../node
          pnpm install
        build-command: ${{ inputs.build_command }}
        preview: ${{ inputs.preview }}
        repo-token: ${{ inputs.repo_token }}
      env:
        VITE_FIREBASE_CONFIG: ${{ inputs.firebase_config }}
